// Generated by gencpp from file diablo_sdk/OSDK_QUATERNION.msg
// DO NOT EDIT!


#ifndef DIABLO_SDK_MESSAGE_OSDK_QUATERNION_H
#define DIABLO_SDK_MESSAGE_OSDK_QUATERNION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace diablo_sdk
{
template <class ContainerAllocator>
struct OSDK_QUATERNION_
{
  typedef OSDK_QUATERNION_<ContainerAllocator> Type;

  OSDK_QUATERNION_()
    : w(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  OSDK_QUATERNION_(const ContainerAllocator& _alloc)
    : w(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef float _w_type;
  _w_type w;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator> const> ConstPtr;

}; // struct OSDK_QUATERNION_

typedef ::diablo_sdk::OSDK_QUATERNION_<std::allocator<void> > OSDK_QUATERNION;

typedef boost::shared_ptr< ::diablo_sdk::OSDK_QUATERNION > OSDK_QUATERNIONPtr;
typedef boost::shared_ptr< ::diablo_sdk::OSDK_QUATERNION const> OSDK_QUATERNIONConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator1> & lhs, const ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator2> & rhs)
{
  return lhs.w == rhs.w &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator1> & lhs, const ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace diablo_sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b94d9692e392e2b3b71fa994a2cf858";
  }

  static const char* value(const ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b94d9692e392e2bULL;
  static const uint64_t static_value2 = 0x3b71fa994a2cf858ULL;
};

template<class ContainerAllocator>
struct DataType< ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator> >
{
  static const char* value()
  {
    return "diablo_sdk/OSDK_QUATERNION";
  }

  static const char* value(const ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32   w\n"
"float32   x\n"
"float32   y\n"
"float32   z\n"
;
  }

  static const char* value(const ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.w);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OSDK_QUATERNION_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::diablo_sdk::OSDK_QUATERNION_<ContainerAllocator>& v)
  {
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIABLO_SDK_MESSAGE_OSDK_QUATERNION_H
