(cl:in-package diablo_sdk-msg)
(cl:export '(LEFT_HIP_ENC_REV-VAL
          LEFT_HIP_ENC_REV
          LEFT_HIP_POS-VAL
          LEFT_HIP_POS
          LEFT_HIP_VEL-VAL
          LEFT_HIP_VEL
          LEFT_HIP_IQ-VAL
          LEFT_HIP_IQ
          LEFT_KNEE_ENC_REV-VAL
          LEFT_KNEE_ENC_REV
          LEFT_KNEE_POS-VAL
          LEFT_KNEE_POS
          LEFT_KNEE_VEL-VAL
          LEFT_KNEE_VEL
          LEFT_KNEE_IQ-VAL
          LEFT_KNEE_IQ
          LEFT_WHEEL_ENC_REV-VAL
          LEFT_WHEEL_ENC_REV
          LEFT_WHEEL_POS-VAL
          LEFT_WHEEL_POS
          LEFT_WHEEL_VEL-VAL
          LEFT_WHEEL_VEL
          LEFT_WHEEL_IQ-VAL
          LEFT_WHEEL_IQ
          RIGHT_HIP_ENC_REV-VAL
          RIGHT_HIP_ENC_REV
          RIGHT_HIP_POS-VAL
          RIGHT_HIP_POS
          RIGHT_HIP_VEL-VAL
          RIGHT_HIP_VEL
          RIGHT_HIP_IQ-VAL
          RIGHT_HIP_IQ
          RIGHT_KNEE_ENC_REV-VAL
          RIGHT_KNEE_ENC_REV
          RIGHT_KNEE_POS-VAL
          RIGHT_KNEE_POS
          RIGHT_KNEE_VEL-VAL
          RIGHT_KNEE_VEL
          RIGHT_KNEE_IQ-VAL
          RIGHT_KNEE_IQ
          RIGHT_WHEEL_ENC_REV-VAL
          RIGHT_WHEEL_ENC_REV
          RIGHT_WHEEL_POS-VAL
          RIGHT_WHEEL_POS
          RIGHT_WHEEL_VEL-VAL
          RIGHT_WHEEL_VEL
          RIGHT_WHEEL_IQ-VAL
          RIGHT_WHEEL_IQ
))