(cl:in-package diablo_sdk-msg)
(cl:export '(CH1-VAL
          CH1
          CH2-VAL
          CH2
          CH3-VAL
          CH3
          CH4-VAL
          CH4
          CH5-VAL
          CH5
          CH6-VAL
          CH6
          CH7-VAL
          CH7
          CH8-VAL
          CH8
          CH9-VAL
          CH9
          CH10-VAL
          CH10
          CH11-VAL
          CH11
          CH12-VAL
          CH12
          CH13-VAL
          CH13
          CH14-VAL
          CH14
          CH15-VAL
          CH15
          CH16-VAL
          CH16
          CH17-VAL
          CH17
          CH18-VAL
          CH18
          FRAME_LOST-VAL
          FRAME_LOST
          FAILSAFE-VAL
          FAILSAFE
          RESERVE-VAL
          RESERVE
))